### ISSUE TITLE
Not working with hhvm 3.8.0

### ISSUE THREAD

**Issue by steelbrain** [RickySu/hhvm-ext-uv#1]
```
In file included from /anees/Sources/hhvm-ext-uv/src/ext.h:6:0,
                 from /anees/Sources/hhvm-ext-uv/src/ext.cpp:1:
/anees/Sources/hhvm-ext-uv/src/util.h: In function ‘int HPHP::resource_to_fd(const HPHP::Resource&)’:
/anees/Sources/hhvm-ext-uv/src/util.h:39:40: error: cannot convert ‘HPHP::SmartPtr<HPHP::File>’ to ‘HPHP::File*’ in initialization
         File *file = fd.getTyped<File>();
                                        ^
/anees/Sources/hhvm-ext-uv/src/util.h:43:44: error: cannot convert ‘HPHP::SmartPtr<HPHP::Socket>’ to ‘HPHP::Socket*’ in initialization
         Socket *sock = fd.getTyped<Socket>();
                                            ^
CMakeFiles/uv.dir/build.make:54: recipe for target 'CMakeFiles/uv.dir/src/ext.cpp.o' failed
make[2]: *** [CMakeFiles/uv.dir/src/ext.cpp.o] Error 1
CMakeFiles/Makefile2:161: recipe for target 'CMakeFiles/uv.dir/all' failed
make[1]: *** [CMakeFiles/uv.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

```
[07:08 PM] steel@Black-Beauty [/anees/Sources/hhvm-ext-uv] {master} $ hhvm --version
HipHop VM 3.8.0 (rel)
Compiler: tags/HHVM-3.8.0-0-gbb32f8d645b28561d8491870c44730b9b3f08d35
Repo schema: 74bee5d310450724cfd49245fd6c2e1e4323b10a
```
